import type { NBAPlayer } from '../src/types';

export const nbaPlayers: NBAPlayer[] = [
  {
    id: 1,
    name: 'LeBron James',
    height: '6 ft 9 in',
    weight: 250,
    country: 'USA',
    college: 'St. Vincent–St. Mary',
    team: 'Los Angeles Lakers',
    position: 'G-F',
  },
  {
    id: 2,
    name: 'Stephen Curry',
    height: '6 ft 2 in',
    weight: 185,
    country: 'USA',
    college: 'Davidson',
    team: 'Golden State Warriors',
    position: 'G',
  },
  {
    id: 3,
    name: 'Kevin Durant',
    height: '6 ft 10 in',
    weight: 240,
    country: 'USA',
    college: 'Texas',
    team: 'Brooklyn Nets',
    position: 'G-F-C',
  },
  {
    id: 4,
    name: 'Giannis Antetokounmpo',
    height: '6 ft 11 in',
    weight: 242,
    country: 'Greece',
    college: 'None',
    team: 'Milwaukee Bucks',
    position: 'F-C',
  },
  {
    id: 5,
    name: 'James Harden',
    height: '6 ft 5 in',
    weight: 220,
    country: 'USA',
    college: 'Arizona State',
    team: 'Philadelphia 76ers',
    position: 'G',
  },
  {
    id: 6,
    name: 'Kawhi Leonard',
    height: '6 ft 7 in',
    weight: 225,
    country: 'USA',
    college: 'San Diego State',
    team: 'Los Angeles Clippers',
    position: 'G-F',
  },
  {
    id: 7,
    name: 'Luka Dončić',
    height: '6 ft 7 in',
    weight: 230,
    country: 'Slovenia',
    college: 'None',
    team: 'Dallas Mavericks',
    position: 'G',
  },
  {
    id: 8,
    name: 'Nikola Jokić',
    height: '6 ft 11 in',
    weight: 284,
    country: 'Serbia',
    college: 'None',
    team: 'Denver Nuggets',
    position: 'C',
  },
  {
    id: 9,
    name: 'Joel Embiid',
    height: '7 ft 0 in',
    weight: 280,
    country: 'Cameroon',
    college: 'Kansas',
    team: 'Philadelphia 76ers',
    position: 'C',
  },
  {
    id: 10,
    name: 'Damian Lillard',
    height: '6 ft 2 in',
    weight: 195,
    country: 'USA',
    college: 'Weber State',
    team: 'Portland Trail Blazers',
    position: 'G',
  },
];
